language: python
python:
    - "3.4"
    - "3.5"
    - "nightly"
branches:
  only:
    - master
    - dev
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements-test.txt
script:
  - py.test --cov
after_success:
  - bash <(curl -s https://codecov.io/bash)